micronaut:
  application:
    name: propostasGrpc
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/proposta-grpc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: Zup@2206
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: create-drop
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true
